name: effective-mobile-users
services:
  users-service:
    build: ./users_service
    networks:
      - backend

  users-actions-service:
    build: ./users_actions_service
    networks:
      - backend

  db:
    image: postgres
    networks:
      - backend

networks:
  backend: